name: GrandmaWantsPics
options:
  bundleIdPrefix: com.grandmawantspics
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 12.9.0

targets:
  GrandmaWantsPics:
    type: application
    platform: iOS
    sources:
      - path: GrandmaWantsPics
        excludes:
          - "Info.plist"
    info:
      path: GrandmaWantsPics/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        NSPhotoLibraryUsageDescription: "We need access to your photo library to send pictures to Grandma."
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
    settings:
      base:
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
