name: GrandmaWantsPics
options:
  bundleIdPrefix: com.grandmawantspics
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 12.9.0

targets:
  GrandmaWantsPics:
    type: application
    platform: iOS
    entitlements:
      path: GrandmaWantsPics/GrandmaWantsPics.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.grandmawantspics.shared
        aps-environment: development
    sources:
      - path: GrandmaWantsPics
        excludes:
          - "Info.plist"
      - path: Shared
    info:
      path: GrandmaWantsPics/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        NSPhotoLibraryUsageDescription: "We need access to your photo library to send pictures to Grandma."
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - grandmawantspics
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - remote-notification
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging
      - target: GrandmaWantsPicsWidgetExtension
        embed: true
    settings:
      base:
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  GrandmaWantsPicsWidgetExtension:
    type: app-extension
    platform: iOS
    productName: GrandmaWantsPicsWidgetExtension
    entitlements:
      path: GrandmaWantsPicsWidget/GrandmaWantsPicsWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.grandmawantspics.shared
    sources:
      - path: GrandmaWantsPicsWidget
      - path: Shared
    info:
      path: GrandmaWantsPicsWidget/Info.plist
      properties:
        CFBundleDisplayName: GrandmaWantsPics Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grandmawantspics.GrandmaWantsPics.WidgetExtension
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: true
